### ISSUE TITLE
Nefungující příklad na kombinaci operátorů

### ISSUE THREAD

**Issue by ZelenyMartin** [pesikj/progr2-python#4]
Ahoj,

v části: http://nove.kodim.cz/czechitas/progr2-python/zaklady-programovani-2/podminky-2/#kombinace-operatoru
ta ukázka nefunguje správně na řádku:
https://github.com/pesikj/progr2-python/blame/master/zaklady-programovani-2/podminky-2/lesson.md#L106

Toto
```
clubMember = input("Jste členem klubu přátel divadla? [ano/ne] ")
if (age <= 26 or age >= 65) and clubMember:
```
bych nahradil za
```
clubMember = input("Jste členem klubu přátel divadla? [ano/ne] ") == "ano"
if (age <= 26 or age >= 65) and clubMember:
```
nebo alespoň
```
clubMember = input("Jste členem klubu přátel divadla? [ano/ne] ")
if (age <= 26 or age >= 65) and (clubMember == "ano"):
```

**Comment by pesikj** [comment]
Díky za upozornění, opraveno.
